name: Ansible-user-with-inventory-file

on:
  workflow_dispatch:
    inputs:
      USER_GROUP:
        type: choice
        required: True
        description: User groups
        options: 
        - devops
        - sre
        - harmony
        - tenable
        - internal
        - qa
        - support
        - portal
      Inventory/:
        required: True
        type: file
      branch:
        required: True
        default: master
        type: string

jobs:
  build:
    runs-on:  [ self-hosted, sre-jenkins ]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: committed file
      uses: test/scripts.sh
      run: cat scripts.sh
