name: containers

on: 
  workflow_dispatch:
    inputs:
      USER_GROUP:
        type: choice
        required: True
        description: User groups
        options: 
        - devops
        - sre

jobs:
  node-version:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine3.15
    steps:
      - name: log node version
        run: |
          node -v 
          cat /etc/os-release
