name: testing FUNCTIONS
on: push

jobs:
  dump-function:
    runs-on: ubuntu-latest
    steps:
      - name: dump FUNCTIONS
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
