name: matrix

on: [push]

jobs:
  node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: node version 
        run: node -v 
      - uses: actions/setup-node@v3
          with:
            node-version: 7
      - name: node version again
        run: node -v
