name: K8 Dev Cassandra Keyspace creation
# Cassandra Keyspace Creation
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
       OCULUS_ENVIRONMENT:
        description: 'Environment to create tables for - used as the suffix for keyspaces created.'
        required: true
        default: 'default'
       BRANCH_NAME:
        description: 'Branch Name'
        required: true
        default: 'develop'
       APP_ID:
        required: true
        default: 'nimble_volstats_lagom'
       NIMBLE_KEYSPACE:
        description: 'environment'
        required: true
        default: 'dev_default'
       CASSANDRA_CONTACT_POINT:
        description: 'DEV Single node in the Cassandra cluster where the keyspaces/tables should be created'
        required: true
        default: '10.174.4.187'
       OCULUS_CASSANDRA_PORT:
        description: 'Port that Cassandra native transport is running on for the specified cluster.'
        required: true
        default: '30042'
       OCULUS_CASSANDRA_REPLICATION:
        description: 'The replication factor to use for the keyspaces created'
        required: true
        default: '3'
       NIMBLE_DEFAULT_LAGOM_CASSANDRA_REPLICATION:
        description: 'replication factor for nimble lagom cassandra'
        required: true
        default: '3'
        
jobs:
  build:
    runs-on: [ self-hosted, lvs-sbt-runner-1.4.7 ]
    env:
      OCULUS_CASSANDRA_PORT: ${{ github.event.inputs.OCULUS_CASSANDRA_PORT }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: run build command
      run: sbt "; project nimble_lagom_impl; set javaOptions += \"-Dconfig.resource=application-lvs.conf\"; set javaOptions += \"-Dcassandra.default.contact-points.0=${{ github.event.inputs.CASSANDRA_CONTACT_POINT }}\" ; runMain nimble.etl.repositories.ASUPFileCreateCassandraTablesCmd"
