name: matrixs

on: [push]

jobs:
  node-versions:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [ 6, 8, 10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: node version 
        run: node -v 
      - uses: actions/setup-node@v3
        with:
            node-version: ${{  matrix.node_version }}
      - name: node version again
        run: node -v
