name: tests

on:
  workflow_dispatch:
    branch:
        required: True
        default: main
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Read Iventory file
      with:
        path: test/script.sh
    - name: read file
      run: cat script.sh
