name: testing
on: push

jobs:
  dump-func:
    runs-on: ubuntu-latest
    steps:
      - name: dump FUNCTIONS
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startswith('hello', 'he') }}
          echo ${{ endswith('hello', 'll') }}
          echo ${{ format('hello {0} {1} {2}', 'world', '!', '!') }}
