name: tests

on:
  workflow_dispatch:
    inputs:
      branch:
        required: True
        default: main
        type: string
      Inventory:
        required: True
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Read package.json
      id: package
      uses: actions/read-file-action@v1
      with:
        path: test/${{ github.event.inputs.Inventory }}
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
