name: tests

on:
  workflow_dispatch:
    branch:
        required: True
        default: main
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Read Iventory file
      run: |
              ls -l
              cat test/script.sh
