name: tests

on:
  workflow_dispatch:
    branch:
        required: True
        default: main
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./scripts.sh
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
